version: "3.7"
services:
  glance-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/glance-ui/src
