version: "3.7"
services:
  glance-ui:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=glance-ui.production
    restart: always
    ports:
      - "8000:80"

