# pull base image
FROM node:15-alpine as builder

# set working directory
WORKDIR /glance-ui

# copy package.json file
COPY package.json .

# install app dependencies
RUN npm install

# copy app
COPY . .

# default ENV
ARG REACT_APP_NAME
ENV REACT_APP_NAME=${REACT_APP_NAME}

# build app
RUN npm run build

##################################
# STEP 2 build a image using NGINX
##################################
FROM nginx:1.19.10-alpine
COPY --from=builder /glance-ui/build /usr/share/nginx/html
