# pull base image
FROM node:15-alpine

# set working directory
WORKDIR /glance-ui

# copy package.json file
COPY package.json .

# install app dependencies
RUN npm install

# copy app
COPY . .

# default ENV
ENV REACT_APP_NAME=localhost

# Expose port
EXPOSE 3000

# Start app
CMD ["npm","start"]